name: Repository Dispatch
on: [push]
jobs:

 uses: rshop/trigger-workflow-action@v1
 with:
  token: ${{ secrets.PATTOKEN }}
  repository: 'https://github.com/LetsGoLearn/QA_Ghostruns'
  workflowId: 12345
