 name: Repository Dispatch
 on: [release]
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PATTOKEN }}
          repository: LetsGoLearn/Dusk_QuickChecks
          event-type: [release]
