name: Repository Dispatch
on: [push]
jobs:
        uses: peter-evans/repository-dispatch@v2.1.2
        with:
                 token: ${{ secrets.PATTOKEN }}
                 repository: https://github.com/LetsGoLearn/QA_Ghostruns
                 event-type: my-event
