name: Dispatch Workflow

on: [push]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2.1.2
      with:
          token: ${{ secrets.PATTOKEN }}
          repository: LetsGoLearn/QA_Ghostruns
          event-type: my-event
