name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PATTOKEN }}
          repository: https://github.com/LetsGoLearn/QA_Ghostruns
          event-type: my-event
